---
title: 'Lab 7 - Correlation (Part 1)'
author: "Student Name"
date: "01/01/2001"
output: 
  html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```


Complete your work in this document before the deadline. Don't forget to update the YAML above.

# Lab Exercise (60 points)

Use the code from the lab instructions to complete this lab exercise.

In this lab exercise, there are two questions to answer. For each question, you will be sampling random numbers from two distributions. To conduct the estimate, you will be running a simulation 100 times.

1. Estimate the mean and standard deviation of correlations (using Pearson's r) that could occur by chance between two random uniform variables with n=10.
`Enter your code below:`




2. Estimate the range (minimum and maximum) of correlations (using Pearons' r) that could occur by chance between two normal random variables with n = 100.

**Hint:** use the `rnorm()` function in R

`Enter your code below:`



3. For the year 2005 ONLY, find the correlation between “perceptions of corruption” and “positive affect”. 




