---
title: 'WA 5 - Descriptive Statistics'
author: "Student Name"
date: "01/01/2000"
output: 
  html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```


## Writing assignment (30 points)


In your own words, write the following. Be sure to use complete and understandable answers. After all, this is a writing assignment. 

1. (5 pts) Define the mode.
2. (5 pts) Explain what would need to happen for a set of numbers to have two modes
3. (5 pts) Define the median
4. (5 pts)Define the mean
5. (10 pts)If one set of numbers had a standard deviation of 5, and another had a standard deviation of 10, which set of numbers would have greater variance, explain why.

**Rubric**

General grading. 

- You will receive 0 points for missing answers (say, if you do not answer question c, then you will receive 0 out of .25 points for that question)
- You must write in complete sentences. Point-form sentences will be given 0 points.
- Completely incorrect answers will receive 0 points. 
- If your answer is generally correct but very difficult to understand and unclear, you may receive half points for the question
